### ISSUE TITLE
部署后访问报错：Cannot read properties of null (reading 'toLowerCase')

### ISSUE THREAD

**Issue by nanqic** [walinejs/netlify-starter#22]
您好，按照文档部署后，页面空白，控制台报错如下：

``` console
 @waline/server  v1.31.9 
init.ts:81 TypeError: Cannot read properties of null (reading 'toLowerCase')
    at zo (index.ts:37:46)
    at Po (config.ts:91:9)
    at WalineComment.vue:153:31
    at ji.fn (reactivity.esm-bundler.js:993:13)
    at ji.run (reactivity.esm-bundler.js:177:19)
    at get value (reactivity.esm-bundler.js:1005:102)
    at setup (WalineComment.vue:156:38)
    at ut (runtime-core.esm-bundler.js:192:19)
    at Cc (runtime-core.esm-bundler.js:7620:25)
    at _c (runtime-core.esm-bundler.js:7581:36)
Ta @ runtime-core.esm-bundler.js:259
Wn @ runtime-core.esm-bundler.js:241
ut @ runtime-core.esm-bundler.js:194
Cc @ runtime-core.esm-bundler.js:7620
_c @ runtime-core.esm-bundler.js:7581
D @ runtime-core.esm-bundler.js:5908
q @ runtime-core.esm-bundler.js:5874
x @ runtime-core.esm-bundler.js:5342
_ @ runtime-core.esm-bundler.js:6018
run @ reactivity.esm-bundler.js:177
u.update @ runtime-core.esm-bundler.js:6142
ge @ runtime-core.esm-bundler.js:6152
D @ runtime-core.esm-bundler.js:5920
q @ runtime-core.esm-bundler.js:5874
x @ runtime-core.esm-bundler.js:5342
qt @ runtime-core.esm-bundler.js:6663
mount @ runtime-core.esm-bundler.js:3928
t.mount @ runtime-dom.esm-bundler.js:1501
Oh @ init.ts:81
（匿名） @ comment:21
显示另外 18 个框架
收起
```

**Comment by lizheming** [comment]
按照教程从头开始重新部署一下

**Comment by nanqic** [comment]
谢谢，是我跳过了前面的vercel部署文档，没有进/ui

**Comment by lizheming** [comment]
哦，不是你的问题，这个是中间版本的 Bug，新版本已修复了，模板里没有更新依赖，我刚合并了依赖升级的 PR.
